### ISSUE TITLE
Holhenzollernbrucke should be named Hohenzollernbruecke instead

### ISSUE THREAD

**Issue by AndreasBaumgart** [grantcarthew/data-stunning#1]
The file `Germany-Holhenzollernbrucke.jpg` should be named `Germany-Hohenzollernbruecke.jpg` instead.

There are two flaws with the original filename:
 - It's Ho**hen**zollern..., not Ho**hel**zollern...*. See: [Wikipedia page of Hohenzollern Bridge in Cologne](https://en.wikipedia.org/wiki/Hohenzollern_Bridge).
 - The correct transcript for the German umlaut *ü* is *ue*. See [Printing conventions in German](https://en.wikipedia.org/wiki/Diaeresis_(diacritic)#Printing_conventions_in_German). I'm assuming German conventions here, since you did not go with the English term (Hohenzollern Bridge).

**Comment by grantcarthew** [comment]
Great spotting @AndreasBaumgart 

Fixed.
